INSERT INTO BLOG_POST_STATUS (BLOG_POST_STATUS_ID, BLOG_POST_STATUS_DESCRIPTION) VALUES (0, 'active');
INSERT INTO BLOG_POST_STATUS (BLOG_POST_STATUS_ID, BLOG_POST_STATUS_DESCRIPTION) VALUES (1, 'withdrawn by author request');
INSERT INTO BLOG_POST_STATUS (BLOG_POST_STATUS_ID, BLOG_POST_STATUS_DESCRIPTION) VALUES (2, 'withdrawn by indexer');

INSERT INTO BLOG_STATUS (BLOG_STATUS_ID, BLOG_STATUS_DESCRIPTION) VALUES (0, 'approved');
INSERT INTO BLOG_STATUS (BLOG_STATUS_ID, BLOG_STATUS_DESCRIPTION) VALUES (1, 'pending');
INSERT INTO BLOG_STATUS (BLOG_STATUS_ID, BLOG_STATUS_DESCRIPTION) VALUES (2, 'rejected');
INSERT INTO BLOG_STATUS (BLOG_STATUS_ID, BLOG_STATUS_DESCRIPTION) VALUES (3, 'withdrawn by owner');
INSERT INTO BLOG_STATUS (BLOG_STATUS_ID, BLOG_STATUS_DESCRIPTION) VALUES (4, 'withdrawn by indexer');

INSERT INTO USER_STATUS (USER_STATUS_ID, USER_STATUS_DESCRIPTION) VALUES (0, 'active');
INSERT INTO USER_STATUS (USER_STATUS_ID, USER_STATUS_DESCRIPTION) VALUES (1, 'inactive by user request');
INSERT INTO USER_STATUS (USER_STATUS_ID, USER_STATUS_DESCRIPTION) VALUES (2, 'inactive by indexer request');

INSERT INTO USER_PRIVILEGE (USER_PRIVILEGE_ID, USER_PRIVILEGE_DESCRIPTION) VALUES (0, 'user');
INSERT INTO USER_PRIVILEGE (USER_PRIVILEGE_ID, USER_PRIVILEGE_DESCRIPTION) VALUES (1, 'moderator');
INSERT INTO USER_PRIVILEGE (USER_PRIVILEGE_ID, USER_PRIVILEGE_DESCRIPTION) VALUES (2, 'admin');

INSERT INTO CLAIM_BLOG_STATUS (CLAIM_BLOG_STATUS_ID, CLAIM_BLOG_STATUS_DESCRIPTION) VALUES (0, 'pending');
INSERT INTO CLAIM_BLOG_STATUS (CLAIM_BLOG_STATUS_ID, CLAIM_BLOG_STATUS_DESCRIPTION) VALUES (1, 'claimed');
INSERT INTO CLAIM_BLOG_STATUS (CLAIM_BLOG_STATUS_ID, CLAIM_BLOG_STATUS_DESCRIPTION) VALUES (2, 'overridden');
INSERT INTO CLAIM_BLOG_STATUS (CLAIM_BLOG_STATUS_ID, CLAIM_BLOG_STATUS_DESCRIPTION) VALUES (3, 'withdrawn by indexer');

INSERT INTO TOPIC_SOURCE (TOPIC_SOURCE_ID, TOPIC_SOURCE_NAME) VALUES (0, 'Post');
INSERT INTO TOPIC_SOURCE (TOPIC_SOURCE_ID, TOPIC_SOURCE_NAME) VALUES (1, 'ScienceSeeker');
INSERT INTO TOPIC_SOURCE (TOPIC_SOURCE_ID, TOPIC_SOURCE_NAME) VALUES (2, 'ResearchBlogging');
